# Generated by Django 5.0.7 on 2025-08-22 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudRenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_nombre', models.CharField(max_length=200)),
                ('unidad_direccion', models.CharField(blank=True, max_length=200)),
                ('unidad_departamento', models.CharField(blank=True, max_length=200)),
                ('resp_nombre', models.CharField(max_length=200)),
                ('resp_telefono', models.CharField(blank=True, max_length=30)),
                ('resp_correo', models.EmailField(max_length=254)),
                ('tipo_adquisicion', models.CharField(choices=[('bienes', 'Adquisición de bienes de consumo o equipamientos'), ('serv_habituales', 'Contratación de servicios habituales'), ('equipos_veh_maq', 'Adquisición de equipos, vehículos o maquinarias'), ('serv_generales', 'Contratación de servicios generales'), ('software_lic', 'Adquisición de softwares, licencias o similares'), ('serv_prof', 'Contratación de servicios profesionales'), ('suministro', 'Suministro de bienes o servicios'), ('obras_civiles', 'Contratación de ejecución de obras civiles')], max_length=30)),
                ('nombre_licitacion', models.CharField(max_length=300)),
                ('modalidad_adjudicacion', models.CharField(choices=[('simple', 'Adjudicación simple'), ('multiple', 'Adjudicación múltiple (por línea)')], max_length=10)),
                ('visita_terreno', models.CharField(choices=[('no', 'No'), ('obligatoria', 'Obligatoria'), ('voluntaria', 'Voluntaria')], default='no', max_length=12)),
                ('visita_lugar', models.CharField(blank=True, max_length=200)),
                ('reunion_informativa', models.CharField(choices=[('no', 'No'), ('obligatoria', 'Obligatoria'), ('voluntaria', 'Voluntaria')], default='no', max_length=12)),
                ('reunion_lugar', models.CharField(blank=True, max_length=200)),
                ('entrega_muestras', models.BooleanField(default=False)),
                ('muestra_lugar', models.CharField(blank=True, max_length=200)),
                ('prueba_tecnica', models.BooleanField(default=False)),
                ('prueba_lugar', models.CharField(blank=True, max_length=200)),
                ('modalidad_contratacion', models.CharField(choices=[('suma_alzada', 'A suma alzada'), ('precios_unitarios', 'Serie de precios unitarios'), ('mixta', 'A suma alzada y serie de precios unitarios'), ('otra', 'Otra modalidad')], max_length=20)),
                ('modalidad_contratacion_otra', models.CharField(blank=True, max_length=200)),
                ('plazo_valor', models.PositiveIntegerField()),
                ('plazo_unidad', models.CharField(choices=[('dias', 'Días corridos'), ('meses', 'Meses')], max_length=10)),
                ('fecha_inicio_contrato', models.DateField(blank=True, null=True)),
                ('monto_contratacion', models.DecimalField(decimal_places=2, max_digits=16)),
                ('moneda', models.CharField(choices=[('CLP', 'Pesos'), ('USD', 'Dólares'), ('UTM', 'UTM'), ('UF', 'UF'), ('OTRA', 'Otra')], default='CLP', max_length=4)),
                ('moneda_otra', models.CharField(blank=True, max_length=30)),
                ('tipo_presupuesto', models.CharField(choices=[('disponible', 'Disponible'), ('referencial', 'Referencial o Estimado')], max_length=12)),
                ('reajustable', models.BooleanField(default=False)),
                ('tipo_financiamiento', models.CharField(choices=[('municipal', 'Municipal'), ('externo', 'Externo')], max_length=10)),
                ('fuente_financiamiento', models.CharField(blank=True, max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
