# Generated by Django 5.0.7 on 2025-08-22 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_solicitudrenca'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiembroComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('unidad', models.CharField(blank=True, max_length=200)),
                ('rol', models.CharField(choices=[('titular', 'Titular'), ('reemplazo', 'Reemplazo')], default='titular', max_length=10)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comision_miembros', to='core.solicitudrenca')),
            ],
        ),
        migrations.CreateModel(
            name='PautaFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('porcentaje', models.PositiveIntegerField(help_text='Debe sumar 100% entre todos los factores.')),
                ('descripcion', models.TextField(blank=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauta_factores', to='core.solicitudrenca')),
            ],
        ),
    ]
