# Generated by Django 5.0.7 on 2025-08-22 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_miembrocomision_pautafactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro', models.PositiveIntegerField(verbose_name='N°')),
                ('causa', models.TextField()),
                ('aplicacion', models.TextField(help_text='Cómo se aplica / condición')),
                ('monto_utm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='core.solicitudrenca')),
            ],
            options={
                'ordering': ['nro'],
            },
        ),
        migrations.CreateModel(
            name='Normativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('numero', models.CharField(blank=True, max_length=60)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('institucion', models.CharField(blank=True, max_length=150)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normativas', to='core.solicitudrenca')),
            ],
        ),
    ]
