# Generated by Django 5.0.7 on 2025-08-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_multa_normativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudrenca',
            name='proposito',
            field=models.TextField(blank=True),
        ),
    ]
