# Generated by Django 5.0.7 on 2025-08-22 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_solicitudrenca_proposito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postulacion',
        ),
    ]
